### ISSUE TITLE
Honour HTTPS_PROXY env variable

### ISSUE THREAD

**Issue by jonsger** [SUSE/connect#489]
It would be nice if SUSEConnect would honour the `HTTPS_PROXY` environment variable.

Because HTTP (without S) doesn't help that much now a days. When firewall block all HTTP traffic...

**Comment by digitaltom** [comment]
SUSEConnect, or better the underlying Ruby HTTP library is reading the HTTP_PROXY env variable and using it for both http and https I think. Did you try that?  

> Because HTTP (without S) doesn't help that much now a days. When firewall block all HTTP traffic... 
SCC isn't even available over http, SUSEConnect by default uses https://scc.suse.com as host. 

General help for setting up proxies under SUSE: https://www.suse.com/support/kb/doc/?id=000017441

**Comment by jonsger** [comment]
My scenario is:
Make a connection from the RMT server to a server with internet connection: `ssh -4 -N -D 9000 user@server-with-internet`

Use `SUSEConnect` with `HTTP(S)_PROXY` variable:

```
HTTP_PROXY=socks5h://localhost:9000 SUSEConnect --debug --write-config https://scc.suse.com --regcode XXX
[...]
opening connection to localhost:9000...
opened
<- "CONNECT scc.suse.com:443 HTTP/1.1\r\nHost: scc.suse.com:443\r\n\r\n"
Conn close because of connect error end of file reached
SUSEConnect error: EOFError: end of file reached
/usr/lib64/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
/usr/lib64/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
/usr/lib64/ruby/2.5.0/net/protocol.rb:167:in `readline'
/usr/lib64/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
/usr/lib64/ruby/2.5.0/net/http/response.rb:29:in `read_new'
/usr/lib64/ruby/2.5.0/net/http.rb:958:in `connect'
/usr/lib64/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/lib64/ruby/2.5.0/net/http.rb:909:in `start'
/usr/lib64/ruby/2.5.0/net/http.rb:1458:in `request'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/connection.rb:83:in `json_request'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/connection.rb:46:in `block (2 levels) in <class:Connection>'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/api.rb:65:in `announce_system'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:106:in `announce_system'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:248:in `announce_or_update'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:27:in `register!'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/cli.rb:49:in `execute!'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/bin/SUSEConnect:11:in `<top (required)>'
/usr/sbin/SUSEConnect:23:in `load'
/usr/sbin/SUSEConnect:23:in `<main>'
```

```
HTTPS_PROXY=socks5h://localhost:9000 SUSEConnect --debug --write-config https://scc.suse.com --regcode XXX
[...]
opening connection to scc.suse.com:443...
[takes quite some time here]
SUSEConnect error: Net::OpenTimeout: execution expired
/usr/lib64/ruby/2.5.0/net/http.rb:937:in `initialize'
/usr/lib64/ruby/2.5.0/net/http.rb:937:in `open'
/usr/lib64/ruby/2.5.0/net/http.rb:937:in `block in connect'
/usr/lib64/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/lib64/ruby/2.5.0/net/http.rb:935:in `connect'
/usr/lib64/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/lib64/ruby/2.5.0/net/http.rb:909:in `start'
/usr/lib64/ruby/2.5.0/net/http.rb:1458:in `request'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/connection.rb:83:in `json_request'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/connection.rb:46:in `block (2 levels) in <class:Connection>'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/api.rb:65:in `announce_system'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:106:in `announce_system'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:248:in `announce_or_update'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/client.rb:27:in `register!'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/lib/suse/connect/cli.rb:49:in `execute!'
/usr/lib64/ruby/gems/2.5.0/gems/suse-connect-0.3.32/bin/SUSEConnect:11:in `<top (required)>'
/usr/sbin/SUSEConnect:23:in `load'
/usr/sbin/SUSEConnect:23:in `<main>'
```

So at least the error messages seem to be a bit different.
This `HTTPS_PROXY=socks5h://localhost:9000`  setup works both with `zypper` and with `rmt-cli`.

**Comment by digitaltom** [comment]
I think the issue here is not that SUSEConnect doesn't use the `HTTPS_PROXY` env, because you can see that it tries to use the proxy connection when provided with `HTTP_PROXY`. But it looks like it cannot deal with that special proxy tunnel setup...

**Comment by felixsch** [comment]
I checked, there is no ruby native implementation for `Socks5` socket types. Sadly this would involve adding an external dependency like `socksify` or commercial library like `chilkat` which is not really feasible right now.

I close this, since it is unlikely we will add `socks5` support soon.

**Comment by thimslugga** [comment]
Just an FYI, when it comes to the usage of the proxy environment variables, you should stick with using the all lowercase variants i.e. `http_proxy` and `https_proxy` as not everything supports the uppercase ones.

https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/
